# Workflow consommateur qui appelle le précédent
name: CI / Sécurité

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  semgrep-check:
    name: Semgrep Security Scan
    uses: ./.github/workflows/semgrep.yml
    with:
      semgrep_config: '.semgrep.yml'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
