# .github/workflows/ci.yml
name: "CI / Sécurité"

on:
  push:
    branches: [ main, 'release/*' ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep-check:
    name: Semgrep Security Scan
    uses: ./.github/workflows/semgrep.yml@main
    with:
      # Chemin vers le fichier de config Semgrep (optionnel)
      semgrep_config: '.semgrep.yml'
    secrets:
      # Permet d’uploader le rapport SARIF dans GHAS
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
