# .github/workflows/ci.yml
name: CI / Sécurité

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  semgrep-check:
    # On appelle ici le workflow réutilisable défini dans semgrep.yml
    uses: ./.github/workflows/semgrep.yml
    with:
      # correspond à l’input semgrep_config déclaré dans semgrep.yml
      semgrep_config: '.semgrep.yml'
    secrets:
      # correspond au secret GH_TOKEN déclaré dans semgrep.yml
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
