# .github/workflows/ci.yml
name: CI / Sécurité

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  semgrep-check:
    name: Semgrep Security Scan
    # Appel du workflow réutilisable
    uses: ./.github/workflows/semgrep.yml
    with:
      # correspond à l'input déclaré dans semgrep.yml
      semgrep_config: '.semgrep.yml'
    secrets:
      # correspond au secret déclaré dans semgrep.yml
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
