name: CI / Sécurité

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep-check:
    uses: ./.github/workflows/semgrep.yml
    with:
      # Facultatif si tu veux utiliser un fichier de config autre que .semgrep.yml
      semgrep_config: '.semgrep.yml'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
