# .github/workflows/ci.yml
name: CI / Sécurité
on:
  push:      { branches: [ main, 'release/*' ] }
  pull_request: { branches: [ main ] }

jobs:
  security-scans:
    uses: ./.github/workflows/security-scans.yml
    with:
      config_path: ".semgrep.yml"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
