# .github/workflows/ci.yml
name: CI / Sécurité

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  semgrep-check:
    name: Semgrep Security Scan
    uses: ./.github/workflows/semgrep.yml  # chemin vers le workflow réutilisable
    with:
      # chemin vers ton fichier de config Semgrep (optionnel)
      semgrep_config: '.semgrep.yml'
    secrets:
      # token pour uploader le SARIF dans GHAS
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
