# .github/workflows/ci.yml  
name: CI / Sécurité

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  semgrep-check:
    # Appel du workflow réutilisable
    uses: ./.github/workflows/semgrep.yml

    # Inputs déclarés dans semgrep.yml (avec workflow_call.inputs)
    with:
      semgrep_config: '.semgrep.yml'

    # Secrets déclarés dans semgrep.yml (avec workflow_call.secrets)
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
